### ISSUE TITLE
ui-timepicker="timePickerOptions" doesn't work

### ISSUE THREAD

**Issue by weicao** [Recras/angular-jquery-timepicker#10]
you cannot access other scope variables except those included in directive's scope, according to angular document  https://docs.angularjs.org/guide/directive

after comment out these code, it works,

   return {
        restrict: 'A',
        require: 'ngModel',
//        scope: {
//            ngModel: '=',
//            baseDate: '=',
//        },

btw, thanks for your great job

**Comment by timmipetit** [comment]
Hi, thanks for reporting this. We switched to an isolated scope to follow the Angular best practices. Can you give a use case when prototypical inherited scope would be better for you?

**Comment by borislit** [comment]
+1

On line 57 $parse(attrs.uiTimepicker)(scope) returns undefined.

**Comment by timmipetit** [comment]
Thanks for finding this issue! Indeed, it seems that passing custom options to uiTimePicker doesn't work at this moment. I will start working on a fix.

**Comment by timmipetit** [comment]
This should be fixed in 0.4.1

**Comment by borislit** [comment]
Thanks. Ill check it out
