### ISSUE TITLE
Mark model invalid if getTime() returns null

### ISSUE THREAD

**Issue by stevenickels** [Recras/angular-jquery-timepicker#12]
The jquery-timepicker control was recently updated to return `null` from its `getTime()` method if the input string is not a valid date. Would it be possible to recognize the null value in the $parser function that calls getTime, and mark the model controller invalid? That way, an angular application using this control can properly recognize when a user has entered an invalid time into the input field, and display error information.

**Comment by timmipetit** [comment]
This sounds like a reasonable request to me. Would you be interested in writing a pull request for this?

**Comment by stevenickels** [comment]
I'd be happy to. I'll try to get it to you within the next day or so.

**Comment by timmipetit** [comment]
Thanks again for the pull requests. I've bumped the version number to 0.4.0

Fixed by PR #13
