### ISSUE TITLE
Github version not working, demo works. 

### ISSUE THREAD

**Issue by Errvald** [Recras/angular-jquery-timepicker#14]
The minified module in the demo works but not the version you have on github.
```
at isAMoment (timepicker.js:16)
    at link.ngModel.$render (timepicker.js:42)
    at Object.ngModelWatch (angular.js:23423)
    at Scope.$get.Scope.$digest (angular.js:14300)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at angular.js:16308
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312
```

I tried removing everything related to moment and it works but the model is ``null``.

The minified version you have in the demo works but it doesn't seem to accept the ``lang`` option.

**Comment by Errvald** [comment]
I defined moment:

```
var moment;
var isAMoment = function(date) {
    return moment !== undefined && moment.isMoment(date) && date.isValid();
};
```

It works ok. Now the problem is when I add ``lang`` in the options, it shows the locale correctly but the ``ngModel`` is no longer updated.

**Comment by Errvald** [comment]
Ok the problem with the ``lang`` option is when you add periods like this: ``{am: 'a.m.'}``, for some reason the model stops updating.

**Comment by timmipetit** [comment]
Could you check if this still breaks with the latest version (0.4.1)? I've fixed a bug could be related to this issue.
