### ISSUE TITLE
Empty input treated as invalid

### ISSUE THREAD

**Issue by hghazzi** [Recras/angular-jquery-timepicker#17]
Hi,

Is there a way to treat an empty input as not invalid? I feel like unless it is merged as required, it should treated as valid.

**Comment by timmipetit** [comment]
That's definitely a good point, we'll look into it!

**Comment by timmipetit** [comment]
Hi @hghazzi, I see that you've been working on this one, nice! Would be be interested in submitting a pull request for your patch?

**Comment by hghazzi** [comment]
Hi, I still need to finish testing it, but once I do, I will create a PR!

**Comment by hghazzi** [comment]
Pull request made.

**Comment by timmipetit** [comment]
Thanks for the PR! I've merged it and bumped the version number.
