### ISSUE TITLE
Required validation is not working 

### ISSUE THREAD

**Issue by Karankang007** [Recras/angular-jquery-timepicker#21]
If ui-timepicker directive is added to an input textbox, validation events are never fired.

Usage:

```
<input id="timepickerTest" name="timepickerTest" ui-timepicker ng-model="myModel" type="text"
                                                class="form-control" required />
```

**Comment by timmipetit** [comment]
Hm.. I can't seem to reproduce the problem that you describe. We also have a specific test for this, that tests for the validation of a required ui-timpicker with blank input: https://github.com/Recras/angular-jquery-timepicker/blob/master/test/timepicker.spec.js#L102
Could you try writing a test for your case?
