### ISSUE TITLE
Object does not have .isValid() method

### ISSUE THREAD

**Issue by jweinstein92** [Recras/angular-jquery-timepicker#23]
In the timepickerdirective.js, the isAMoment() takes in a moment object, however `date.isValid()` fails. To fix, surround date in moment(): `moment(date).isValid()`

**Comment by timmipetit** [comment]
Could you give an example (or even better: a test) of when/how this fails? We first check wether the object is a moment using `moment.isMoment(date)`, so I don't see how it fails.
