### ISSUE TITLE
Object does not have .toDate() method

### ISSUE THREAD

**Issue by jweinstein92** [Recras/angular-jquery-timepicker#24]
In timepickerdirective.js in the ngModel.$render method, after checking if date is a moment, `date = date.toDate()` is called, causing an error. To fix, surround date in moment(): `moment(date).toDate()`

Also, in the asDate method, if baseDate is true, baseDate does not have the method .toDate. baseDate should be surrounded by moment(): moment(baseDate).toDate()

**Comment by timmipetit** [comment]
Could you give an example (or even better: a test) of when/how this fails?
