### ISSUE TITLE
TypeError: Cannot set property 'time' of undefined

### ISSUE THREAD

**Issue by ftferes** [Recras/angular-jquery-timepicker#26]
I am using angular-jquery-timepicker and when my page is loaded I catch this error:

"TypeError: Cannot set property 'time' of undefined."

It occurs at line 91-92 in timepickerdirective.js

Take a look:

File: timepickerdirective.js

if(element.is('input'))  {
              ngModel.$parsers.unshift(function(viewValue){
                    var date = element.timepicker('getTime', asDate() );
                    return date ? asMomentOrDate(date) : date;
                });
(line 91)   ngModel.$validators.time = function(modelValue){
(line 92)        return (!attrs.required && !userInput()) ? true : isDateOrMoment(modelValue);
                };
            }

**Comment by timmipetit** [comment]
This is probably because you are using an older version of AngularJS. It seems that `$validators` is available in 1.3 and higher. We'll update our requirements, thanks.

**Comment by Jozkee** [comment]
what happens if I took it off?
