### ISSUE TITLE
NPM project is out of date

### ISSUE THREAD

**Issue by StuartMorris** [Recras/angular-jquery-timepicker#29]
https://www.npmjs.com/package/angular-jquery-timepicker

Is npm expected to be kept current for this project as well, or Bower only?

**Comment by timmipetit** [comment]
Ah sorry for that, we want to keep the npm project current, but publishing to npm doesn't seem to be in our muscle memory. Thanks for mentioning this!

**Comment by jaeggir** [comment]
@timmipetit can you push the latest release to npm again? thx.

**Comment by timmipetit** [comment]
@jaeggir: latest version was not properly versioned yet. Just pushed version 0.12.0 to fix this, also available on NPM.
