### ISSUE TITLE
jquery-timepicker-jt version in package.json

### ISSUE THREAD

**Issue by gergderkson** [Recras/angular-jquery-timepicker#31]
The [jQuery plugin](https://github.com/jonthornton/jquery-timepicker) just updated to version 1.9.0.
When we ran `bower install` on our project, it stopped angular-jquery-timepicker working and started throwing the following error:

```
application.min.js?1461075017:7 TypeError: Cannot read property 'getHours' of null
    at t
    at w.setTime 
    at a.fn.timepicker
    at ngModel.$render
```

I assume this is because in `package.json` the jquery plugin is listed as a depedancy with the version `>=1.2`. Should this be changed to avoid `bower install` pulling in breaking changes?

I resolved this on my end by putting this into our projects `bower.json` =>  `"jquery-timepicker-jt": "1.2"`

**Comment by timmipetit** [comment]
Hah, good point! I think we should find out which version of `jquery-timepicker-jt` still works with this directive, so that we could give a range (`"1.2 - 1.8"` for example).

**Comment by timmipetit** [comment]
It seems that we're not compatible with jquery-timepicker >= 1.9. I've updated our bower file accordingly and pushed a new tag (0.9.2). Thanks for reporting!
