### ISSUE TITLE
angular-jquery-timepicker not working with webpack?

### ISSUE THREAD

**Issue by brianpchsu** [Recras/angular-jquery-timepicker#36]
Hi, I've been trying to use angular-jquery-timepicker with webpack. However, I keep seeing the error that the app `failed to instantiate module angular-jquery-timepicker`. I imported the angular-jquery-timepicker module and verified that it's in the vendor.js and vendor.bundle.js. Does angular-jquery-timepicker support to be used with webpack? Is there anything I need to do to use it? Thanks.

**Comment by henryng24** [comment]
Same issue. Also getting this error with this library and other ones.

**Comment by timmipetit** [comment]
We have not used this library with webpack yet, so it could definitely be the case that it's not compatible yet. Do you know what would need to change to make it work? We're always open for good pull requests.

**Comment by vadimivanov** [comment]
I have decision for my project (Angular 1.5 + webpack + es6).

bower install angular-jquery-timepicker

//index.js
import 'jquery-timepicker-jt';
import 'angular-jquery-timepicker';

const app = angular.module('app', ['ui.timepicker'])

it works for me

**Comment by timmipetit** [comment]
Thanks for the information @vadimivanov! @henryng24 and @brianpchsu, could you confirm that this method works?
