### ISSUE TITLE
Possible to change it to 24-hour format?

### ISSUE THREAD

**Issue by GeorgeTsilias** [Recras/angular-jquery-timepicker#37]
Is it possible to change the timepicker to the 24-hour format?

**Comment by timmipetit** [comment]
Yes, you can use all options from https://github.com/jonthornton/jquery-timepicker, as can be seen in the documentation of this project.  To change the time format, use something like:

```
$scope.timePickerOptions = {
    timeFormat: 'H:i',
};

<input ui-timepicker="timePickerOptions" ng-model="someDateObject">
```
