### ISSUE TITLE
Localisation for Germany 24hrs time format

### ISSUE THREAD

**Issue by rksbala** [Recras/angular-jquery-timepicker#40]
Facing 24hrs time format for Germany language.

scope.startTime = moment({ hour: '00'}) // default '00' set as default time. Even tried with js date obj also.

//Timepicker options:
scope.timePickerOptions: {
    lang: {
        am: 'uhr',
        pm: 'uhr'
    },
    show2400: true,
    timeFormat: 'H:ia'
};

<input id="time-start" ui-timepicker="scope.timePickerOptions" ng-model="scope.startTime" />

**Below issues facing:**
1. In timepicker dropdown 24hrs time is formatted, when click the list by default '12:00uhr' is selected / hightlighted. PFA screenshots below.
![image](https://cloud.githubusercontent.com/assets/6780344/26505062/d6ca1bae-4264-11e7-9bbe-7bc7746a7743.png)
![image](https://cloud.githubusercontent.com/assets/6780344/26505081/ebe3756c-4264-11e7-863e-df1252b403bb.png)
2. When I selected '05:00uhr' but in the list '17:00uhr' is highlighted, this value (17:00uhr) only updated in ng-model.
![image](https://cloud.githubusercontent.com/assets/6780344/26505129/26cc7c96-4265-11e7-9763-504ca08e99a5.png)
Can you please suggest what is wrong here? 
Tried with jquery also http://jsfiddle.net/rksbala/1xLmnhpq/1/

**Comment by timmipetit** [comment]
I think this is a bug in jQuery timepicker, and not in the Angular bindings, since the bug also shows in your jsfiddle. So I would suggest to open an issue here: https://github.com/jonthornton/jquery-timepicker
Furthermore, this seems to be caused by using the same string for the `am` and `pm` format.

**Comment by rksbala** [comment]
Thank you. 
The issue already raised https://github.com/jonthornton/jquery-timepicker/issues/615
