### ISSUE TITLE
Manual assignment changes the date

### ISSUE THREAD

**Issue by Miqueliu** [Recras/angular-jquery-timepicker#46]
When the time is writed, date is modified and put as: January 1st, 1970.

**Comment by timmipetit** [comment]
Could you provide an example how/where this exactly happens?

**Comment by Miqueliu** [comment]
It happens with any example. [Here](https://codepen.io/anon/pen/PvaWJg) is one.

**Comment by timmipetit** [comment]
This is because during the typing the model is updated and the time is probably invalid at the time. When this happens, the model is set to null. You can use `base-date` to work around this.

**Comment by Miqueliu** [comment]
So, it would be nice if base date defaults to current date or from `ngModel` value.

**Comment by timmipetit** [comment]
We currently have no intention to change this behaviour ourselfs, but we're happy to accept merge requests.
