### ISSUE TITLE
Getting the right version of jquery timepicker from npm

### ISSUE THREAD

**Issue by mattcasey** [Recras/angular-jquery-timepicker#48]
Hello! First, thanks for this module it saved me a bunch of time.

However, I wasted a couple hours because I did `npm install jquery-timepicker`. It surprisingly mostly works with this library, except ng-model never gets updated. After scouring previous issues here, I noticed there's no npm dependency listed for the timepicker dependency. After searching online for `jquery-timepicker-jt`, I found that the correct npm package is called, simply `timepicker`: https://github.com/jonthornton/jquery-timepicker.

I'd like to add something for the next person, either an update to package.json to specify `timepicker@1.8` or add it to the README where you show how to install via npm. Thoughts?

**Comment by timmipetit** [comment]
Hi Matt,

Sounds like a good idea to add `timepicker` to the list of npm dependencies. We were using Bower when we started working on this library, but that has been deprecated now.

**Comment by mattcasey** [comment]
cool, i will try to submit a PR when i have a chance this week!
