### ISSUE TITLE
Moment support?

### ISSUE THREAD

**Issue by bramski** [Recras/angular-jquery-timepicker#7]
![screen shot 2015-01-28 at 12 27 11 pm](https://cloud.githubusercontent.com/assets/421781/5946232/06a48cb6-a6e9-11e4-8755-3901fbe87fc1.png)

**Comment by timmipetit** [comment]
Hi Bram,

You're right, angular-jquery-timepicker currently doesn't support momentjs. Would you be interested in writing a pull request for this?

**Comment by bramski** [comment]
https://github.com/Recras/angular-jquery-timepicker/pull/8

**Comment by timmipetit** [comment]
Fixed by #8
